apache/tika

tika-server/src/test/java/org/apache/tika/server/TikaDetectorsTest.java

The testGetJSON() method had a strange cast to (Object) that I removed to improve readability and maintainability. This was identified by findbugs rule BC_IMPOSSIBLE_CAST.

Code Quality Fix for Findbugs Rule Impossible Cast

---

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml

Updated Mime-Magic for 6 mime types:
1. application/postscript :  files begin with pattern "%!PS-Adobe-3.0 EPSF-3.0".
2. application/wordperfect: files begin with pattern "ÿWPC" .
3. image/tiff : updated pattern for "MM.+" for Big endian format.(occur at the beginning of files of tiff mime type)
4. application/rdf+xml : updated pattern "rdf" ( from byte offset 5 to 400) 
5. application/atom+xml : updated pattern "feed" ( from byte offset 5 to 50)
6. application/rss+xml : updated pattern "rss" ( from byte offset 5 to 50)

Fix for TIKA-1881

---

tika-translate/src/main/java/org/apache/tika/language/translate/YandexTranslator.java
tika-translate/src/main/resources/org/apache/tika/language/translate/translator.yandex.properties
tika-translate/src/test/java/org/apache/tika/language/translate/YandexTranslatorTest.java

Support for Yandex "Translate API" Service

fix for TIKA-1943 contributed by Mark Duske

---

tika-parsers/src/main/java/org/apache/tika/parser/html/HtmlHandler.java
tika-parsers/src/test/java/org/apache/tika/parser/html/HtmlParserTest.java

Adds HtmlParser support for `<script>` tags within `<head>`.

fix for TIKA-1938 contributed by naegelejd

---

tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRConfig.java
tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRParser.java
tika-parsers/src/main/resources/org/apache/tika/parser/ocr/TesseractOCRConfig.properties
tika-parsers/src/test/java/org/apache/tika/parser/ocr/TesseractOCRParserTest.java

Small change to Tesseract OCR code to add the hOCR outputType.   In the future we can add `pdf` and `tsv` as output types as well.
First patch to Tika, please provide feedback!

add hOCR output format to TesseractParser   TIKA-2093

---

tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRConfig.java
tika-parsers/src/test/java/org/apache/tika/parser/ocr/TesseractOCRConfigTest.java

I also improved and added more test cases.

TIKA-2231: Improved param validation of TesseractOCRConfig.setLanguage()

---

tika-parsers/src/main/java/org/apache/tika/parser/pdf/AbstractPDF2XHTML.java
tika-parsers/src/main/java/org/apache/tika/parser/pdf/PDFParser.java
tika-parsers/src/main/java/org/apache/tika/parser/pdf/PDFParserConfig.java
tika-parsers/src/main/resources/org/apache/tika/parser/pdf/PDFParser.properties

Added a new option parameter on PDFParserConfig for
extract bookmarks from a PDF. Its name is extractBookmarksText.

Fix for TIKA-2303 contributed by ppalazon.

---

tika-parsers/src/main/java/org/apache/tika/parser/font/TrueTypeParser.java
tika-parsers/src/test/java/org/apache/tika/parser/font/FontParsersTest.java

The TrueTypeParser opens fonts during parsing, however it never closes
these resources. This causes a slow file handle leak that causes
problems when processing large amounts of fonts.
This change wraps the font resource in a try-finally block to ensure
that the resource is closed after parsing has occurred.

TrueTypeParser Close Open Fonts

---

tika-parsers/src/main/java/org/apache/tika/parser/microsoft/POIFSContainerDetector.java

Change file magic number from byte[] literal to a byte array determined by an ASCII string literal.

POIFSContainerDetector ASCII-encoded magic number

---

tika-nlp/src/main/java/org/apache/tika/parser/recognition/AgeRecogniser.java

This PR fixes a typo in exception message and adjusts the code indentation, keeping tabs as used in other parts of the code.

Fix a typo in log message, and adjust code indentation

---

tika-parsers/src/main/java/org/apache/tika/parser/microsoft/xml/WordMLParser.java

In case SUPPORTED_TYPES is ever changed back to a set containing more than one value, a reminder to use an immutable container such as `Collections.unmodifiableSet(set)`.
This is a continuation of #193.

SUPPORTED_TYPES is immutable

---

tika-langdetect/src/main/java/org/apache/tika/langdetect/OptimaizeLangDetector.java

TIKA-2439 throwing IllegalStateException in OptimaizeLangDetector.detectAll if no module have been loaded and thus detector is null which avoid an unhelpful NullPointerException

TIKA-2439 throwing IllegalStateException in OptimaizeLangDetector.detectAll

---

tika-parsers/src/main/java/org/apache/tika/parser/recognition/tf/TensorflowRESTRecogniser.java
tika-parsers/src/main/resources/org/apache/tika/parser/recognition/tf/InceptionRestDockerfile
tika-parsers/src/main/resources/org/apache/tika/parser/recognition/tf/inceptionapi.py
tika-parsers/src/test/java/org/apache/tika/parser/recognition/ObjectRecognitionParserTest.java
tika-parsers/src/test/resources/org/apache/tika/parser/recognition/tika-config-tflow-rest.xml

**Support all image formats in Object Recognition REST Parser**
Currently object recognition REST parser only supports parsing jpeg image type. Objective of this task is to add all image format support to it by converting any image into jpeg format at the server's end.

Fix for TIKA-2402

---

tika-parsers/src/main/java/org/apache/tika/parser/microsoft/HSLFExtractor.java

This avoids the ambiguous error `org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.OfficeParser`.

Convert EncryptedPowerPointFileException to EncryptedDocumentException

---

tika-dl/src/main/java/org/apache/tika/dl/imagerec/DL4JInceptionV3Net.java

cfr. discussion at https://github.com/apache/tika/pull/182#issuecomment-324757211
cc @chrismattmann

bump read timeout for downloading file to 60s (1min) in tika-dl

---

tika-batch/src/test/java/org/apache/tika/batch/fs/BatchProcessTest.java

While installing Tika 1.16, I was running into this cryptic test failure:
```
java.lang.AssertionError: expected:<0> but was:<42>
```
At first, I was a bit confused, since `42` is clearly a superior result compared to `0`... [1]
After doing some digging, it turns out that I had `$_JAVA_OPTIONS` defined, which results in a message like this to stderr every time `java` is called:
```
Picked up _JAVA_OPTIONS: ...
```
I had to change the failing test to directly compare the stderr output with the empty string rather than checking the length of the strings to figure out what was wrong, so I propose to change this.
[1] https://en.wikipedia.org/wiki/42_(number)#The_Hitchhiker.27s_Guide_to_the_Galaxy

directly compare stderr to empty string in testRedirectionOfStreams to obtain more meaningful messages if test fails

---

tika-parsers/src/main/resources/org/apache/tika/parser/recognition/tf/InceptionVideoRestDockerfile

Added 'pip install flask requests pillow' instead of 'pip install flask requests'

TIKA-2464: No PIL found when building docker file 'InceptionVideoRestDockerfile'

---

tika-parsers/src/main/java/org/apache/tika/parser/mail/MailContentHandler.java
tika-parsers/src/main/java/org/apache/tika/parser/mail/RFC822Parser.java
tika-parsers/src/test/java/org/apache/tika/parser/mail/RFC822ParserTest.java

https://issues.apache.org/jira/browse/TIKA-1788 old case but had the solution in it. Not sure why it never made it in.
There is other info available in `MaximalBodyDescriptor`. However I am not sure how they would map to fields in `Metadata` or if most files would even have that info*.
One piece of info that I would like to make available is either the whole `Content-Disposition` line which I am not sure how to get, or flags for `attachment`/`inline` that are almost always available with filename. Looking at the source code, it is parsed but hidden away behind a `private` field.😢

[TIKA-1788] RFC822Parser: provide email attachment filenames when available

---

tika-parsers/src/main/java/org/apache/tika/parser/pdf/PDFParser.java
tika-parsers/src/main/java/org/apache/tika/parser/pdf/PDFParserConfig.java
tika-parsers/src/main/resources/org/apache/tika/parser/pdf/PDFParser.properties
tika-parsers/src/test/resources/org/apache/tika/parser/pdf/tika-inline-config.xml

Expose a maxMainMemoryBytes property in the PDFParserConfig which the
PDFParser uses to construct a MemoryUsageSetting and pass that to
PDDocument.load

Fix OOM when parsing very large PDFs

---

tika-core/src/main/java/org/apache/tika/fork/ClassLoaderProxy.java
tika-core/src/test/java/org/apache/tika/fork/ForkParserTest.java
tika-core/src/test/java/org/apache/tika/fork/ForkTestParser.java
tika-core/src/test/java/org/apache/tika/fork/unusedpackage/ClassInUnusedPackage.java

`ForkParser` can not be used right now when using `AutoDetectParser` together with the optional `jai-imageio-core` dependency.
This fix enhances the patch provided in TIKA-1191 with unit tests.
Thanks for the great work with Apache Tika! It would be really helpful for us to be able to use `ForkParser` with all optional dependencies in a future version.

TIKA-1191 fix package access in ForkParser

---

tika-parsers/pom.xml
tika-translate/pom.xml

Upgrade use of jackson to 2.9.4.  Versions 2.9.2 and 2.9.3 allow
unauthenticated remote code execution, labeled CVE-2017-17485.

Fix for TIKA-2570 contributed by ewanmellor.

---

tika-core/src/main/java/org/apache/tika/sax/SafeContentHandler.java

Fix doc comment regarding the replacement character used by
SafeContentHandler.  This comment has been incorrect since TIKA-698
(Sep 2011).

Fix for TIKA-2580 contributed by ewanmellor.

---

tika-parent/pom.xml

Hi,
as TIKA is my Maven test project for new versions of forbiddenapis and the local test build already succeeded (before my release), here is a PR that updates to new version. It also removes the commons-io hack in the parent pom.

Update forbiddenapis to version 2.5 and remove commons-io hack

---

tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRConfig.java
tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRParser.java

Tesseract 4.0 includes a change to use form feed characters to separate
pages by default in its text output. Previous versions used no separator
unless you specified the include_page_breaks option.
This confuses any parser that is not expecting the FF.
ODFParserTest.testOO2Metadata fails, because it is expecting the output of
a blank image to be the empty string, but now the FF is there.
I haven't seen any other failures, but I expect that user code will now see
either FF or U+FFFD where they are not expecting it (SafeContentHandler
replaces the FF with U+FFFD when converting to text to XML).
Fix this by setting Tesseract's page_separator option to the empty string.
This will preserve the no-page-breaks behavior with both Tesseract 3.x and
4.0.
Also, add an option …

Fix for TIKA-2582 contributed by ewanmellor.

---

tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRConfig.java
tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRParser.java

Add TesseractOCRConfig.{add,get}OtherTesseractConfig, plus parsing of
TesseractOCRConfig.properties to extract any key-value pair where the key
has an underscore.
Inside TesseractOCRParser, pass these key-value pairs to Tesseract using
its -c command line option.
This gives a mechanism by which user code can pass arbitrary options to
Tesseract without Tika having to understand them.
This PR depends on PR #222 / TIKA-2582 because of merge conflicts.

Fix for TIKA-2584 contributed by ewanmellor.

---

tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRConfig.java
tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRParser.java

Change -psm on the Tesseract command line to --psm, with two dashes.
This matches a change in Tesseract 4.0 to remove the one-dash version.
It has been deprecated since Nov 2016.
The Tesseract cset is ee201e1f4.
Also, move the config file (i.e. getOutputType in Tika's terms) so that it
is the last parameter on the command line.  Tesseract logs an error
message (though otherwise doesn't fail) if the config file is not the
last thing on the command line.
This PR depends upon PR #224 / TIKA 2584 and PR #222 / TIKA-2582 because of merge conflicts.

Fix for TIKA-2613 contributed by ewanmellor.

---

tika-langdetect/src/main/java/org/apache/tika/langdetect/OptimaizeLangDetector.java

When using tika-server, every single call triggers loadModel and
this method is very CPU intensive.
Optimaize uses immutable objects so we can easily reuse the
default model when no configuration is provided, it's a
20x improvement for my workload.

TIKA-2520 optimize OptimaizeLangDetector default loadModel()

---

tika-parsers/src/main/java/org/apache/tika/parser/odf/OpenDocumentParser.java
tika-parsers/src/test/java/org/apache/tika/parser/odf/ODFParserTest.java
tika-parsers/src/test/resources/test-documents/testODTnotaZipFile.odt

- throw IOException if ZipInputStream is invalid or does not contain any entries
Note: now the behavior on empty zip files is different, if called on a local file (succeeds, empty document) or not (fails). The OpenDocument format spec ([section 17.2](http://docs.oasis-open.org/office/v1.1/OS/OpenDocument-v1.1.pdf), cf. [wikipedia article](https://en.wikipedia.org/wiki/OpenDocument_technical_specification#Format_internals)) does not state anything about empty zip files.

TIKA-2675 OpenDocumentParser should fail on invalid zip files

---

tika-parsers/pom.xml

Excluded commons-logging and commons-logging-api from dependencies of uimafit-core.

fix for TIKA-2690 contributed by HansBrende

---

tika-core/src/main/java/org/apache/tika/mime/MimeType.java
tika-core/src/main/java/org/apache/tika/mime/MimeTypes.java
tika-core/src/main/java/org/apache/tika/mime/MimeTypesReader.java
tika-core/src/main/java/org/apache/tika/mime/MimeTypesReaderMetKeys.java
tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
tika-core/src/test/java/org/apache/tika/mime/CustomReaderTest.java
tika-core/src/test/java/org/apache/tika/mime/MimeDetectionTest.java
tika-core/src/test/resources/org/apache/tika/mime/custom-mimetypes2.xml

mime detection based on resource name used to detect
the mime-type of "http://example.com/test.php" as being "text/x-php"
whereas given such an URL, the file extension doesn't give
us any information about the mime type that will be returned
by the server

TIKA-2648 : detect interpreted server-side scripting languages

---

tika-parent/pom.xml

This mainly adds support for Java 11 class files/signatures and silences the commons-io warnings for modules that don't use commons-io.

Update forbiddenApis to version 2.6

---

tika-core/src/main/java/org/apache/tika/utils/XMLReaderUtils.java

As part of the changes introduced in 1.19 `determineMaxEntityExpansions` needs to read the `jdk.xml.entityExpansionLimit` System Property in order to overwrite the default value of 20, if it is set.
This is however by reading all System Properties with `System#getProperties()` and attempting to find the relevant key in the properties Object. The issue with this approach is that `System#getProperties()` requires:
```
java.util.PropertyPermission "*", "read,write"
```
which is an overly permissive one to allow for the given use case.
A more sane approach, following the least privilege design principal would be to use `System.getProperty()` for the specific property that only requires
```
java.util.PropertyPermission "jdk.xml.entityExpansionLimit", "read"
```

fix for TIKA-2731 contributed by @jkakavas

---

tika-core/src/test/java/org/apache/tika/TestRereadableInputStream.java
tika-core/src/test/java/org/apache/tika/fork/ForkParserTest.java
tika-langdetect/src/test/java/org/apache/tika/langdetect/LanguageDetectorTest.java
tika-parsers/src/main/java/org/apache/tika/parser/crypto/Pkcs7Parser.java
tika-parsers/src/test/java/org/apache/tika/parser/fork/ForkParserIntegrationTest.java
tika-parsers/src/test/java/org/apache/tika/parser/pkg/CompressParserTest.java
tika-parsers/src/test/java/org/apache/tika/parser/solidworks/SolidworksParserTest.java

This pull request was created automatically as part of our ongoing efforts
at https://diffblue.com to implement refactorings. Feel free to leave feedback
here or contact us directly for any enquiries.
The developer in charge is @krobelus.
**Changes**:
- Replace try statements that close a resource in the finally block with a
try-with-resources statement [1].
[1] https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

Use try-with-resources

---

tika-core/src/main/java/org/apache/tika/mime/MimeTypesReader.java

Prevents an NPE from spilling out of MimeTypesReader.read() when the calling thread is interrupted. See https://issues.apache.org/jira/projects/TIKA/issues/TIKA-2896 for more details.

TIKA-2896 Null check before releasing parser in MimeTypesReader

---

tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRParser.java

Figuring out what is going on when you call out to third party processsors can be hard, provide some extra detail when the user runs in --verbose mode.

When running in --verbose mode, log the parameters to Tesseract

---

tika-server/README.md

introduce the Docker image, bump some versions, link to the right place on the wiki.
I changed the versions to all be 1.24, but maybe everything needs to be 2.0-SNAPSHOT??

TIKA-3037 Update docs for Tika Server

---

tika-parent/pom.xml

This hides all warnings caused by commons-io not used in all modules (cf. new mojo parameter).
See https://github.com/policeman-tools/forbidden-apis/wiki/Changes#version-30-released-2020-04-27

Add support for forbiddenapis 3.0

---

tika-core/src/main/java/org/apache/tika/config/TikaConfigSerializer.java
tika-core/src/main/java/org/apache/tika/mime/MimeTypesReader.java
tika-core/src/main/java/org/apache/tika/utils/XMLReaderUtils.java

The OWASP guide (https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.md) recommends that external DTD + Stylesheets be disabled for TransformerFactory instances.

Disable external DTD + Stylesheets with the TransformerFactory

---

tika-server/src/main/java/org/apache/tika/server/resource/RecursiveMetadataResource.java

see https://issues.apache.org/jira/browse/TIKA-3133
and https://issues.apache.org/jira/browse/TIKA-3126
this will add new parameters to `rmeta` rest endpoint
`writeLimit` - max number of characters to store; if < 0, the handler will store all characters
`maxEmbeddedResources` - number of embedded resources that will be parsed. if < 0, it will handle unlimited embedded resources.
This will make it so we can control how many embedded docs will be parsed in a call to rmeta, and how many bytes will be written to the body.

TIKA-3133 - writeLimit and maxEmbeddedResources for recursive parsing - add header

---

tika-advanced-parser-modules/tika-parser-nlp-module/src/main/resources/META-INF/services/org.apache.tika.parser.Parser

CTAKESParser should not load via the parser service loader because it will cause an infinite loop.
If `org.apache.tika.parser.ctakes.CTAKESParser` in file `org.apache.tika.parser.Parser`:
1. `org.apache.tika.config.ServiceLoader#loadStaticServiceProviders(Class<T>)` will create a new instance for `org.apache.tika.parser.ctakes.CTAKESParser`
2. `org.apache.tika.parser.ctakes.CTAKESParser#CTAKESParser()` will create a new instance for `org.apache.tika.config.TikaConfig` and then will call `org.apache.tika.config.ServiceLoader#loadStaticServiceProviders(Class<T> )` to load another `org.apache.tika.parser.ctakes.CTAKESParser`.
It's a infinite loop, Should remove CTAKESParser from file org.apache.tika.parser.Parser.

Fix infinite loop in tika-parser-nlp-module

---

tika-example/pom.xml
tika-server/pom.xml

The `tika-parsers` is not generating `test-jar` with the recent commit `a504d7e`, but `tika-server` and `tika-examples` are still using it as dependency. This would lead to the building failure, and this PR is a fix for it.
Such kind of problems could not be easily found with local builds and jenkins builds - both of them have maven cache in `~/.m2/`. To find these problems needs cleaning all cache before maven building, and for most of time this is pretty time consuming.
I'm thinking about if we should add `Github Actions` building for Tika(see also PR [#333](https://github.com/apache/tika/pull/333)). It seems that actions could build without any cache, and it's downloading dependency pretty fast.
Ideas?

Remove dependency tika-parsers test-jar in tika-server and tika-examples

---

tika-parser-modules/tika-parser-code-module/src/test/java/org/apache/tika/parser/sas/SAS7BDATParserTest.java

Use short months in default language to test.

Fix test fail in SAS7BDATParserTest caused by default language is not english

---

tika-batch/src/main/java/org/apache/tika/batch/builders/BatchProcessBuilder.java

We want to know if string "reporter" it's keyNodes's key instead of if null it's keyNodes's key.
So I think this a typo and this PR is a fix for it.

Fix key typo in BatchProcessBuilder

---

tika-core/src/main/java/org/apache/tika/config/TikaConfig.java

Trying to fix Tika-3141 with a empty string check in `TikaConfig`

Tika-3141 : add empty environment variable handle

---

tika-translate/pom.xml

Jenkins's job `tika-main-jdk11` and `tika-main-jdk14` build fail caused by depenency conflict in component `tika-translate`.
Here is the full log: 
[tika-main-jdk11 build 22](https://ci-builds.apache.org/job/Tika/job/tika-main-jdk11/22/console), 
[tika-main-jdk14 build 6](https://ci-builds.apache.org/job/Tika/job/tika-main-jdk14/6/console)
Here is the failed part of the log:
```
Dependency convergence error for jakarta.activation:jakarta.activation-api:1.2.2 paths to dependency are:
+-org.apache.tika:tika-translate:2.0.0-SNAPSHOT
+-org.apache.cxf:cxf-rt-rs-client:3.4.0
+-jakarta.xml.soap:jakarta.xml.soap-api:1.4.2
+-jakarta.activation:jakarta.activation-api:1.2.2
and
+-org.apache.tika:tika-translate:2.0.0-SNAPSHOT
+-com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.11.2 …
```

Fix Jenkins build error on JDK11 and JDK14

---

tika-bundle/pom.xml

Jenkins's job `tika-branch1x-jdk11` build fail caused by depenency conflict in `tika-bundle`.
Here is the full log: [tika-branch1x-jdk11 build 7](https://ci-builds.apache.org/job/Tika/job/tika-branch1x-jdk11/7/console)
Here is the failed part of the log:
```
Dependency convergence error for jakarta.activation:jakarta.activation-api:1.2.2 paths to dependency are:
+-org.apache.tika:tika-bundle:1.25-SNAPSHOT
+-org.apache.tika:tika-parsers:1.25-SNAPSHOT
+-org.apache.cxf:cxf-rt-rs-client:3.4.0
+-jakarta.xml.soap:jakarta.xml.soap-api:1.4.2
+-jakarta.activation:jakarta.activation-api:1.2.2
and
+-org.apache.tika:tika-bundle:1.25-SNAPSHOT
+-jakarta.activation:jakarta.activation-api:1.2.1
```
This PR is a fix for this

Fix Jenkins build error on JDK11 build 7

---

tika-parser-modules/tika-parser-integration-tests/src/test/java/org/apache/tika/parser/TabularFormatsTest.java

As `TODO` says , should check the % format again after https://github.com/epam/parso/issues/28 fixed.
Modify `table` use regular expression matching because `testXLS`, `testXLSX` and `testXLSB` also should check the % format.

Modify TabularFormatsTest

---

tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/detect/microsoft/ooxml/OPCPackageDetector.java

Method `fillSet` in `OPCPackageDetector` can be more simple.

Refactor fillSet in OPCPackageDetector

---

tika-core/src/main/java/org/apache/tika/language/detect/LanguageDetector.java
tika-core/src/main/java/org/apache/tika/language/translate/DefaultTranslator.java
tika-core/src/main/java/org/apache/tika/utils/CompareUtils.java
tika-core/src/main/java/org/apache/tika/utils/ServiceLoaderUtils.java

Add CompareUtils, remove duplicate code and simplify some sort.

Add CompareUtils and simplify some sort

---

tika-batch/src/test/java/org/apache/tika/batch/fs/BatchProcessTest.java
tika-batch/src/test/java/org/apache/tika/batch/fs/FSBatchTestBase.java
tika-core/src/test/java/org/apache/tika/TikaTest.java
tika-core/src/test/java/org/apache/tika/config/TikaConfigTest.java
tika-parser-modules/tika-parser-font-module/src/test/java/org/apache/tika/parser/font/FontParsersTest.java
tika-parser-modules/tika-parser-html-module/src/test/java/org/apache/tika/parser/html/HtmlParserTest.java
tika-parser-modules/tika-parser-integration-tests/src/test/java/org/apache/tika/detect/TestContainerAwareDetector.java
tika-parser-modules/tika-parser-integration-tests/src/test/java/org/apache/tika/parser/RecursiveParserWrapperTest.java
tika-parser-modules/tika-parser-integration-tests/src/test/java/org/apache/tika/parser/pkg/CompositeZipContainerDetectorTest.java
tika-parser-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/chm/TestChmExtraction.java
tika-parser-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/ooxml/TruncatedOOXMLTest.java
tika-parser-modules/tika-parser-miscoffice-module/src/test/java/org/apache/tika/parser/odf/ODFParserTest.java
tika-parsers-extended/tika-parser-scientific-module/src/test/java/org/apache/tika/parser/gdal/TestGDALParser.java

1. Add method `getResourceAsUrl` to `TikaTest`
2. Add method `getResourceAsUri` to `TikaTest`
3. Simplify some test code by using method `TikaTest#getResourceAsUrl` and `TikaTest#getResourceAsUri`

Simplify some test code by using method TikaTest#getResourceAsUrl and TikaTest#getResourceAsUri

---

tika-core/src/test/java/org/apache/tika/TikaTest.java
tika-eval/src/test/java/org/apache/tika/eval/SimpleComparerTest.java

1. Fix file exist judgement in method TikaTest#getResourceAsFile
In method [TikaTest#getResourceAsFile](https://github.com/apache/tika/blob/4696bd6cbc021c96bc64f63e8cea2ab8f3092ba3/tika-core/src/test/java/org/apache/tika/TikaTest.java#L109), there is a file exist judgement:
```
File file = new File(new File(uri), name);
if (file == null) {
fail("Unable to find requested file " + name);
}
```
The result of `file==null` is always true.  Should be replaced with `!file.exists()`.
2.  Fix test error in test case SimpleComparerTest
Fix file can't find in method `testChinese`. 
Test file don't exist. Use method `Paths.get`.
Fix file name typo in method `testTagsOutOfOrder`.
Change file name typo from "file16_badtags.html" to "file16_badTags.html".
This typo won't affect `windows` because file …

Fix file exist judgement in method TikaTest#getResourceAsFile

---

tika-core/src/main/java/org/apache/tika/sax/CleanPhoneText.java
tika-core/src/main/java/org/apache/tika/sax/DIFContentHandler.java
tika-core/src/test/java/org/apache/tika/mime/ProbabilisticMimeDetectionTestWithTika.java
tika-parser-modules/tika-parser-integration-tests/src/test/java/org/apache/tika/parser/ocr/TesseractOCRParserTest.java
tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/AbstractListManager.java
tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/AbstractPOIFSExtractor.java
tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ListManager.java
tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/SXSLFPowerPointExtractorDecorator.java
tika-parser-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/dif/DIFContentHandler.java
tika-parser-modules/tika-parser-miscoffice-module/src/test/java/org/apache/tika/parser/hwp/HwpV5ParserTest.java
tika-parsers-advanced/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/ner/regex/RegexNERecogniser.java
tika-parsers-extended/tika-parser-scientific-module/src/main/java/org/apache/tika/parser/geoinfo/GeographicInformationParser.java

1. Simplify some call of `StringBuilder#append`.
2. Simplify some call of `String#substring`.
3. Remove unnecessary call of `#toString`.

Simplify some call of String operation

---

tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/detect/microsoft/ooxml/OPCPackageDetector.java

Remove two private methods : `closeQuietly(ZipFile)`, `closeQuietly(ZipEntrySource)`.
Replace call with method `closeQuietly(Closeable)` from commons-compress.

Replace two redundant methods in OPCPackageDetector

---

tika-core/src/main/java/org/apache/tika/detect/CompositeEncodingDetector.java
tika-core/src/main/java/org/apache/tika/embedder/ExternalEmbedder.java
tika-core/src/test/java/org/apache/tika/metadata/filter/TestMetadataFilter.java
tika-parser-modules/tika-parser-font-module/src/main/java/org/apache/tika/parser/font/AdobeFontMetricParser.java
tika-parser-modules/tika-parser-html-module/src/main/java/org/apache/tika/parser/html/DefaultHtmlMapper.java
tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/SummaryExtractor.java
tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/XSSFExcelExtractorDecorator.java
tika-parser-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java

Simplify some loop by use method Collection.addAll and method Arrarys.asList

Simplify some loop by use method Collection.addAll and method Arrarys.asList

---

tika-parser-modules/tika-parser-pkg-module/src/main/java/org/apache/tika/parser/pkg/PackageParser.java

Method `SevenZFile` use byte[]-arg version for the password is deprecated.
Use the char[]-arg version for the password instead.

Remove deprecated method call in PackageParser

---

tika-core/src/main/java/org/apache/tika/io/TikaInputStream.java

In method `getPath`, copy data from InputStream to a temporary file should use current TikaInputStream.
Otherwise the variable of TikaInputStream `position` will not update.
There is not meaning if `position` is not real position.

Modify TikaInputStream

---

tika-parser-modules/tika-parser-text-module/src/main/java/org/apache/tika/parser/txt/UniversalEncodingListener.java

According to these web pages: [Windows-1252 Chraracter list](https://www.fileformat.info/info/charset/windows-1252/list.htm) , [ISO-8859-1 Chraracter list](http://www.fileformat.info/info/charset/ISO-8859-1/list.htm), [ISO-8859-15 Chraracter list](https://www.fileformat.info/info/charset/ISO-8859-15/list.htm)
There are 5 byte values ( 0x81, 0x8d, 0x8f, 0x90, 0x9d ) that charset Windows-1252 don't has but charset ISO-8859-1 and  charset ISO-8859-15 have.
I think we can add one more judgment condition:  if content has these byte values , means charset isn't Windows-1252

Add more judge between Charset Windows-1252 and ISO-8859-1(5)

---

tika-core/src/main/java/org/apache/tika/sax/TextAndAttributeContentHandler.java
tika-parser-modules/tika-parser-xml-module/src/main/java/org/apache/tika/parser/xml/TextAndAttributeXMLParser.java
tika-parser-modules/tika-parser-xml-module/src/test/java/org/apache/tika/parser/xml/TextAndAttributeXMLParserTest.java

[TIKA-2001](https://issues.apache.org/jira/browse/TIKA-2001) requires a XML parser which can output text and attributes.
This PR would like to provide it.
User can config `TextAndAttributeXMLParser` as parser of `application/xml`.

TIKA-2001: Add TextAndAttributeContentHandler and TextAndAttributeXMLParser

---

tika-bundles/tika-bundle-classic/pom.xml

I notice there is a test error in tika-bundle-classic if JDK's version bigger than 8.
See is this [Jenkins log](https://ci-builds.apache.org/job/Tika/job/tika-main-jdk11/lastBuild/org.apache.tika$tika-bundle-classic/console)
This PR is a fix for it. 
I have tested on windows with JDK8 and ubuntu with JDK11, and it work.  WDYT :)

Fix test error of tika-bundle-classic module

---

tika-core/src/main/java/org/apache/tika/Tika.java

Replace with `return parseToString(stream, metadata, maxStringLength);`

Simplify method Tika#parseToString(InputStream, Metadata)

---

tika-batch/src/main/java/org/apache/tika/batch/builders/BatchProcessBuilder.java
tika-batch/src/main/java/org/apache/tika/batch/builders/CommandLineParserBuilder.java
tika-core/src/main/java/org/apache/tika/detect/FileCommandDetector.java
tika-core/src/main/java/org/apache/tika/extractor/ParsingEmbeddedDocumentExtractor.java
tika-core/src/main/java/org/apache/tika/parser/digest/CompositeDigester.java
tika-core/src/main/java/org/apache/tika/parser/digest/InputStreamDigester.java
tika-core/src/test/java/org/apache/tika/parser/mock/MockParser.java
tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/XMLErrorLogUpdater.java
tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/io/DBWriter.java
tika-fuzzing/src/main/java/org/apache/tika/fuzzing/pdf/EvilCOSWriter.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-apple-module/src/main/java/org/apache/tika/detect/apple/BPListDetector.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-jdbc-commons/src/main/java/org/apache/tika/parser/jdbc/AbstractDBParser.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-jdbc-commons/src/main/java/org/apache/tika/parser/jdbc/JDBCTableReader.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/HSLFExtractor.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/AbstractPDF2XHTML.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/ImageGraphicsEngine.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/OCR2XHTML.java
tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFMarkedContent2XHTML.java
tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/java/org/apache/tika/parser/sqlite3/SQLite3DBParser.java
tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/resource/UnpackerResource.java

We used to use` IOExceptionWithCause` because `IOException` with the `Throwable` constructors is missing before `JDK 6`.
I think we should use `IOException` after `JDK 6`.

Use IOException instead of IOExceptionWithCause

---

tika-server/tika-server-classic/pom.xml

Was looking to spin a tika-docker for the 2.0.0-ALPHA (yay!) and saw the tika-server-classic isn't loading.
Good news is following this change my test suites in a couple of applications I use Tika in have pass nicely.
Updated tika-docker is ready to go once tika-server-classic is updated and republished.

Removed exclusion of tika-server-core from tika-server-classic

---

tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-pdf-module/pom.xml

I found there is a test error in `tika-parser-pdf-module` with JDK11.
See this log:
```
[ERROR] org.apache.tika.parser.pdf.PDFPreflightParserTest.testBasic  Time elapsed: 0.019 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/activation/DataSource
at org.apache.tika.parser.pdf.PDFPreflightParserTest.testBasic(PDFPreflightParserTest.java:48)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
at org.apache.tika.parser.pdf.PDFPreflightParserTest.testBasic(PDFPreflightParserTest.java:48)
```
I think we should add back dependency `jaxb-runtime` for tika-parser-pdf-module.

Add back dependency jaxb-runtime for tika-parser-pdf-module

---

tika-server/src/main/java/org/apache/tika/server/ProduceTypeResourceComparator.java
tika-server/src/main/java/org/apache/tika/server/TikaServerCli.java
tika-server/src/test/java/org/apache/tika/server/CXFTestBase.java

Added Resource comparator based to produce type.
In an ambiguous call, request handler will be chosen based on the type of data it returns.
**Current priority is set as:**
MediaType.TEXT_PLAIN_TYPE,
MediaType.APPLICATION_JSON_TYPE,
MediaType.TEXT_XML_TYPE,
MediaType.TEXT_HTML_TYPE
**The lower in list (higher index value), the higher priority it has.**
In case of no matching in this list, it will be treated as media type all.
**_Note: Please change priority list if some other order is more suitable._**

[TIKA-3357] removes ambiguity by choosing handler based on produce type

---

tika-translate/src/main/java/org/apache/tika/language/translate/RTGTranslator.java
tika-translate/src/main/resources/META-INF/services/org.apache.tika.language.translate.Translator
tika-translate/src/test/java/org/apache/tika/language/translate/RTGTranslatorTest.java

RTG translator (https://isi-nlp.github.io/rtg/) integration to tika-translate 
This service requires running RTG model for 500-eng translation as a REST service
By default, the RTGTranslator uses `http://localhost:6060` as base URL 
Which can be obtained from a prebuilt docker image:
* docker image can be run on CPU (i.e. without GPU, for testing):
`docker run --rm -i -p 6060:6060 tgowda/rtg-model:500toEng-v1`
* but GPU (e.g. Device 0) is recommended for translating a lot of documents:
`docker run --rm -i -p 6060:6060 --gpus '"device=0"' tgowda/rtg-model:500toEng-v1`
`rtg.base.url` property from `translator.rtg.properties` file can be  used to customize base URL if needed. 
CC @chrismattmann  @tballison

fix for TIKA-3329 contributed by Thamme Gowda

---

tika-example/pom.xml
tika-example/src/main/java/org/apache/tika/example/TranscribeTranslateExample.java
tika-parent/pom.xml
tika-transcribe/pom.xml
tika-transcribe/src/main/java/org/apache/tika/transcribe/AmazonTranscribe.java
tika-translate/src/main/java/org/apache/tika/language/translate/GoogleTranslator.java

This issue addresses https://issues.apache.org/jira/browse/TIKA-3403
In addition to implementing the example file, it proposes the following improvements
* minor upgrade of aws libraries to `1.11.1018`
* adds a new configuration option for the AWS transcriber allowing client to write to a specific region cf. `transcribe.REGION`
* makes use of [SelectObjectContentRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/SelectObjectContentRequest.html) which filters the contents of an Amazon S3 object (transcription) based on a simple Structured Query Language (SQL) statement. In the request, along with the SQL expression, we specify JSON as the data serialization format of the object. Amazon S3 uses this to parse object data into records, and returns …

TIKA-3403 Create example for Transcription

---

tika-core/src/main/java/org/apache/tika/parser/AutoDetectParser.java

Previously TIKA-860 added getter and setters to make Zip bomb prevention
configurable but because SecureContentHandler is create inline in
AutoDetectParser we have no access to these parameters.
This change adds a configuration object that can be set and used when
constructing the SecureContentHandler inline.
- …

[TIKA-860] Allow for AutoDetectParser to specify SecureContentHandler parameters.

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-audiovideo-module/src/main/java/org/apache/tika/parser/mp3/Mp3Parser.java

Fix some broken links in a javadoc

---

tika-core/pom.xml
tika-core/src/main/java/org/apache/tika/config/ConfigBase.java
tika-core/src/main/java/org/apache/tika/config/ServiceLoader.java
tika-core/src/main/java/org/apache/tika/config/TikaConfig.java
tika-core/src/main/java/org/apache/tika/detect/NameDetector.java
tika-core/src/main/java/org/apache/tika/detect/TrainedModelDetector.java
tika-core/src/main/java/org/apache/tika/language/detect/LanguageNames.java
tika-core/src/main/java/org/apache/tika/metadata/Property.java
tika-core/src/main/java/org/apache/tika/metadata/filter/NoOpFilter.java
tika-core/src/main/java/org/apache/tika/mime/ProbabilisticMimeDetectionSelector.java
tika-core/src/main/java/org/apache/tika/parser/RecursiveParserWrapper.java
tika-core/src/main/java/org/apache/tika/parser/external/ExternalParser.java
tika-core/src/main/java/org/apache/tika/parser/external/ExternalParsersConfigReader.java
tika-core/src/main/java/org/apache/tika/pipes/HandlerConfig.java
tika-core/src/main/java/org/apache/tika/pipes/PipesReporter.java
tika-core/src/main/java/org/apache/tika/pipes/PipesResult.java
tika-core/src/main/java/org/apache/tika/utils/AnnotationUtils.java

Including changes in pom.xml for Findbugs
To get report use command: mvn clean compile site
and check the folder site in target.

TIKA-3649 Perform findbugs static analysis on the project and address the issues

---

CHANGES.txt
tika-core/src/test/java/org/apache/tika/metadata/TestMetadata.java
tika-parent/pom.xml
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-image-module/src/main/java/org/apache/tika/parser/image/ImageMetadataExtractor.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-image-module/src/test/java/org/apache/tika/parser/image/ImageMetadataExtractorTest.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-image-module/src/test/java/org/apache/tika/parser/image/JpegParserTest.java

Fixes TIKA-3815.
Actually Drew Noakes metadata-extractor library uses **GMT** timezone when timezone is not specified since version 2.8.1, not JVM default:
[fix tests to work on different timezones](https://github.com/drewnoakes/metadata-extractor/commit/1899deac8af55934363183dae605e286bc79afa3)
So I changed the code to reflect that and updated tests. Now `user.timezone` doesn't need to be fixed to UTC anymore to run tests, they should work on any timezone.
I would like some other committer to test this to be sure tests work on a timezone different than mine (GMT-3)

TIKA-3815: set GMT timezone for unspecified timezones like drew noakes,

---

tika-core/src/main/java/org/apache/tika/fork/ForkClient.java
tika-core/src/test/java/org/apache/tika/fork/ForkParserTest.java
tika-core/src/test/java/org/apache/tika/fork/ForkTestParser.java

ForkClient to check for thread interrupted status when waiting for response. Add test to ForkParserTest to demonstrate issue and fix.

[TIKA-3825] ForkClient to check for thread interrupted status when waiting for response

---

tika-core/src/main/java/org/apache/tika/fork/ForkClient.java
tika-core/src/test/java/org/apache/tika/fork/ForkParserTest.java
tika-core/src/test/java/org/apache/tika/fork/ForkTestParser.java

ForkClient to check for thread interrupted status when waiting for response. Add test to ForkParserTest to demonstrate issue and fix. Targeting branch_1x

[TIKA-3825] ForkClient to check for thread interrupted status

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/fork/ForkParserIntegrationTest.java

stop using hard coded port in test ForkParserIntegrationTest

TIKA-3881 - use dynamic port for test ForkParserIntegrationTest

---

CHANGES.txt
tika-parent/pom.xml
tika-parsers/tika-parsers-ml/tika-age-recogniser/pom.xml
tika-parsers/tika-parsers-ml/tika-parser-nlp-module/pom.xml

Affects `tika-parser-nlp-module` and `tika-age-recognizer` (presumably deprecated)

TIKA-3935 Remove log4j 1.2.x from dependencies

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-package/pom.xml

`tika-parsers-standard-package` is a shaded JAR and the pom.xml keeps the transitive dependencies used to generate the shaded JAR

Create dependency reduced pom.xml for tika-parsers-standard-package

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/util/BitReader.java

Context
---
CPU profiling of OneNoteParser shows that a lot of cpu time is spent creating the BitSet in `BitReader`. Reusing the byte array reference will prevent the need to make a copy of the byte array.
Template
---
- and placed in front of your commit messages surrounded by square brackets (`[TIKA-XXXX] Issue …

[TIKA-3979] OneNoteParser - Improve performance for deserialization

---

tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/journal/GrobidRESTParser.java
tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/ner/grobid/GrobidNERecogniser.java
tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/resources/org/apache/tika/parser/journal/GrobidExtractor.properties
tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/resources/org/apache/tika/parser/ner/grobid/GrobidServer.properties

TIKA JIRA issue: https://issues.apache.org/jira/browse/TIKA-4112
This PR updates the grobid (github.com/kermitt2/grobid) and grobid-quantities (github.com/kermitt2/grobid-quantities) parsers
- default URLS for both parsed 
- added try-catch when checking whether the service is alive

Update Grobid parsers

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/xps/XPSExtractorDecorator.java

- Type of change :
Fix a flaky test, caused by nondeterministic iteration order of HashMap
[org.apache.tika.parser.microsoft.ooxml.xps.XPSParserTest.testVarious](https://github.com/lxb007981/tika/blob/971f0cbd9b46c1d7fb96b0a3732c3fc870920aba/tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/ooxml/xps/XPSParserTest.java#L59)
https://github.com/lxb007981/tika/blob/d466492e0a01c8ee28c108bc3022f1a03ff530de/tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/xps/XPSExtractorDecorator.java#L119
When recursively extracting metadata from an XPS file, a simple `HashMap` is used and iterated. However, note that …

[TIKA-4165] fix a flaky test.

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/main/java/org/apache/tika/parser/html/JSoupParser.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/test/java/org/apache/tika/parser/html/HtmlParserTest.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/test/resources/test-documents/testHTML_script_in_body.html

Hey there. I spotted that public signup to Tika Jira is disabled, so I'm not sure what is the correct flow for issues without a ticket, putting all related info here...
`org.apache.tika.parser.html.JSoupParser` parser ignores `body` content after the `script` tag. Check `org.apache.tika.parser.html.HtmlParserTest#testScriptInBody` test for details.
The main reason of such behaviour is that `#data` tag tail decrements `org.apache.tika.parser.html.HtmlHandler.bodyLevel`, when `#data` tag head is considered a content node and doesn't invoke `startElement` logic at all. As a fix I mirrored head logic for the data node to the tail and returned `FilterResult.CONTINUE` early.

Fix html parsing logic when body contains script tag

---

CHANGES.txt
README.md
tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
tika-core/src/test/java/org/apache/tika/TikaDetectionTest.java
tika-core/src/test/java/org/apache/tika/mime/MimeTypesReaderTest.java
tika-core/src/test/java/org/apache/tika/mime/ProbabilisticMimeDetectionTest.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/mime/TestMimeTypes.java

Fixes [TIKA-4119](https://issues.apache.org/jira/browse/TIKA-4119).
Additionally, I've added support for ".mjs" files, as documented in the RFC:
> Additional information:
>
> Deprecated alias names for this type: application/javascript, application/x-javascript, text/javascript1.0, text/javascript1.1, text/javascript1.2, text/javascript1.3, text/javascript1.4, text/javascript1.5, text/jscript, text/livescript
> 
> Magic number(s): N/A
> **File extension(s): .js, .mjs**
> Macintosh File Type Code(s): TEXT

[TIKA-4119]: Return media type "text/javascript" instead of "application/javascript" to follow RFC-9239

---

tika-pipes/tika-emitters/tika-emitter-jdbc/src/main/java/org/apache/tika/pipes/emitter/jdbc/JDBCEmitter.java

TIKA-4190 - set autocommit to false in jdbc emitter

---

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml

Fixes the issue that some pkcs12 keystores are not correctly detected. Tested with 157x p12 keystores (kindly provided by [redhat](https://github.com/redhat-qe-security/keyfile-corpus/tree/master).)

[TIKA-4194] Fix for unrecognized pkcs12 keystores

---

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml

TIKA-4225 -- add detection for amf

---

tika-core/src/main/java/org/apache/tika/pipes/PipesServer.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/EmptyFetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/Fetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/RangeFetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/fs/FileSystemFetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/url/UrlFetcher.java
tika-core/src/test/java/org/apache/tika/pipes/async/MockFetcher.java
tika-core/src/test/java/org/apache/tika/pipes/fetcher/MockFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-az-blob/src/main/java/org/apache/tika/pipes/fetcher/azblob/AZBlobFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-gcs/src/main/java/org/apache/tika/pipes/fetcher/gcs/GCSFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-http/src/main/java/org/apache/tika/pipes/fetcher/http/HttpFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-s3/src/main/java/org/apache/tika/pipes/fetcher/s3/S3Fetcher.java

TIKA-4252: add request metadata

---

tika-core/src/main/java/org/apache/tika/pipes/PipesServer.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/EmptyFetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/Fetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/RangeFetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/fs/FileSystemFetcher.java
tika-core/src/main/java/org/apache/tika/pipes/fetcher/url/UrlFetcher.java
tika-core/src/test/java/org/apache/tika/pipes/async/MockFetcher.java
tika-core/src/test/java/org/apache/tika/pipes/fetcher/MockFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-az-blob/src/main/java/org/apache/tika/pipes/fetcher/azblob/AZBlobFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-gcs/src/main/java/org/apache/tika/pipes/fetcher/gcs/GCSFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-http/src/main/java/org/apache/tika/pipes/fetcher/http/HttpFetcher.java
tika-pipes/tika-fetchers/tika-fetcher-s3/src/main/java/org/apache/tika/pipes/fetcher/s3/S3Fetcher.java

revert accidentally merged prs with failing tests

Revert bad commits

---

tika-grpc/pom.xml

Exclude plugin metadata from shaded JAR.

Circumvention for MNG-8180 Maven bug

---

tika-app/src/main/java/org/apache/tika/gui/TikaGUI.java

TIKA-4290: Need to use returned value of substring()

TIKA-4290: Need to use returned value of substring()

---

tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/journal/TEIDOMParser.java

Without them  "Author [surName=" + surName + ", middleName=" + middleName expression is compared with null and obviously it's never null

TIKA-4290 Need round brackets around ternary operator. 

---

tika-serialization/src/main/java/org/apache/tika/serialization/ParseContextDeserializer.java
tika-serialization/src/main/java/org/apache/tika/serialization/ParseContextSerializer.java
tika-serialization/src/main/java/org/apache/tika/serialization/TikaJsonSerializer.java
tika-serialization/src/main/java/org/apache/tika/serialization/pipes/JsonFetchEmitTuple.java

TIKA-4294 -- improve serialization of ParseContext

---

tika-core/src/main/java/org/apache/tika/detect/MagicDetector.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/chm/ChmItsfHeader.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/chm/ChmItspHeader.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/GUID.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/dbf/DBFColumnHeader.java

TIKA-4290 Change the way to output Arrays. Previously they were output as hex addresses in memory

TIKA-4290 Change the way to output Arrays.

---

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml

The audio/x-aac is deprecated, and replaced by audio/aac. Having audio/aac as an alias for the deprecated type makes it possible to recognize the audio/aac MIME type.

[TIKA-4300] Add audio/aac as an alias for the audio/x-aac MIME type

---

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml

This makes it possible to recognize the standard audio/flac MIME type

 [TIKA-4304] Add audio/flac as an alias to the audio/x-flac MIME type

---

tika-core/src/main/java/org/apache/tika/Tika.java

Changes made:
try-with-resources is used to automatically handle closing the InputStream, ensuring that it is always closed properly without the need for a finally block.

[TIKA-4290] Refactor parseToString method to use try-with-resources

---

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml

https://issues.apache.org/jira/browse/TIKA-4312
tika-mimetypes.xml currently defines these two <sub-class-of> ancestor chains:
- audio/mp4 → application/quicktime.
- video/mp4 → video/quicktime → application/quicktime.
Based on [RFC 4337, section 2](https://datatracker.ietf.org/doc/html/rfc4337#section-2), it is my understanding that audio/mp4 is a special case of video/mp4. I thus suggest changing the ancestor chain of audio/mp4 to 
- audio/mp4 → video/mp4 → video/quicktime → application/quicktime

[TIKA-4312] Make audio/mp4 a subclass of video/mp4

---

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml

A follow-up to #1947: Support 32-bit and 64-bit Mach-O files and detect their type
cc @tballison

[TIKA-4309] detailed Mach-O in tika-mimetypes.xml

---

tika-core/src/main/resources/org/apache/tika/parser/external/tika-external-parsers.xml

Sox tool correctly pulls duration from wav files. I haven't seen any tests for external parsers anywhere.
Sample output from sox --info duration-test-3.wav:
Input File : 'duration-test-3.wav'
Channels : 1
Sample Rate : 44100
Precision : 16-bit
Duration : 00:00:02.50 = 110298 samples = 187.582 CDDA sectors
File Size : 221k
Bit Rate : 706k
Sample Encoding: 16-bit Signed Integer PCM

[TIKA-3637] Adding sox audio tool to external parsers

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/xps/XPSPageContentHandler.java

Fixes exceptions raised and poor content parsing for XPS files.
These fixes in the first commit are for the exceptions:
- NPE when indices attribute is not present
- Parse errors when parsing indices string, we only need the advance so I've simplified this parsing to just grab that float which is in the second comma separated value
In the second commit these are improvements to text extractions:
- Don't assume glyph runs appear in vertical order
- Check for VisualBrush transform which moves child canvases
- Use the entire canvas stack for keying the canvas map instead of just the last one
- Split GlyphRuns with large gaps into two glyph runs because in some cases another glyph run will be positioned in that gap meaning the extracted text order needs to be different.
- Fix text direction …

[TIKA-4337] Fix XPS regressions

---

tika-app/src/test/java/org/apache/tika/cli/TikaCLITest.java
tika-core/src/main/java/org/apache/tika/metadata/HTML.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/main/java/org/apache/tika/parser/html/HtmlHandler.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/test/java/org/apache/tika/parser/html/HtmlParserTest.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFParser.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java

TIKA-4357 -- improve metadata key prefixing for PDFs and html

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/libpst/LibPstParser.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/libpst/LibPstParserConfig.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/libpst/TestLibPstParser.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/fork/ForkParserIntegrationTest.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/resources/configs/tika-config-lib-pst.xml

TIKA-4355 -- LibPstParserConfig should be serializable

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-zip-commons/src/main/java/org/apache/tika/detect/zip/JarDetector.java

TIKA-4365 : Support added for Android AAB bundle file. 
Detection is through AndroidManifest.xml similar to APK files in JarDetector. As per Android Developer Documentation this file is seen in manifest directory. 
https://developer.android.com/guide/app-bundle/app-bundle-format

TIKA-4365 : feat : Support Detection for AAB Bundle file

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/xps/XPSPageContentHandler.java

TIKA-4337 -- check for empty string in array index 1

---

tika-parent/pom.xml

- jackcess-encrypt depends on an older version of  jackcess
- jackcess-encrypt now uses org.bouncycastle:bcprov-jdk18on rather than org.bouncycastle:bcprov-jdk15on
By updating the exclusions we avoid dependency convergence errors in projects using Tika.

TIKA-4417: fix dependency convergence error with jackcess-encrypt

---

CHANGES.txt
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/detect/microsoft/POIFSContainerDetector.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/detect/TestContainerAwareDetector.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/resources/configs/tika-4441-120.xml
tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/resources/configs/tika-4441-12000000.xml
tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/resources/configs/tika-4441-neg1.xml

TIKA-4441 -- revert markLimit and add unit tests

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-cad-module/pom.xml

The original value appears to have been copied from the "code" module. Compiling an upstream project complains of a conflict with the code module.

[TIKA-4457] Updating Automatic-Module tag for cad module.

---

tika-server/tika-server-standard/bin/tika

Returning "1" after calling the start method seems wrong. The solr start script, which seems to be the origin of the tika one, has since fixed this by using $? instead.

Return correct result code from start script

---

tika-core/src/main/java/org/apache/tika/sax/AbstractRecursiveParserWrapperHandler.java

TIKA-4453 -- slight mods

---

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-audiovideo-module/src/main/java/org/apache/tika/detect/MatroskaDetector.java
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-audiovideo-module/src/main/resources/META-INF/services/org.apache.tika.detect.Detector
tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-audiovideo-module/src/test/java/org/apache/tika/detect/MatroskaDetectorTest.java

This PR introduces a `MatroskaDetector` to more accurately identify MKV and WEBM files based on EBML headers and DocType strings. It improves detection in cases where:
- File extensions are missing
- DocType is compressed, shifted, or partially missing
- Signatures in tika-mimetypes.xml alone are insufficient
Includes:
- `MatroskaDetector.java`
- Test file: `MatroskaDetectorTest.java`
- `META-INF/services/org.apache.tika.detect.Detector` entry
Benchmarked against:
- Default Tika
- Wladimir Leite's mime-type additions
- This detector
Results indicate this approach improves detection accuracy in nuanced cases not handled by mime magic alone.

TIKA-1180: Add MatroskaDetector for improved MKV/WEBM detection

---

tika-core/pom.xml

Fixes TIKA-4392. Makes xerces optional in OSGI imports. Tested in my OSGI environment (equinox).
I have decided to use "TIKA-*:" format for git messages - other commits use it instead of "bracket rule".
Based on current main. Rebasing to branch_3_2x is trivial.

TIKA-4392: core osgi requirements now list xerces as optional

---

CHANGES.txt
tika-core/src/main/java/org/apache/tika/config/TikaTaskTimeout.java
tika-pipes/tika-pipes-core/src/main/java/org/apache/tika/pipes/core/PipesClient.java
tika-pipes/tika-pipes-core/src/main/java/org/apache/tika/pipes/core/PipesServer.java
tika-pipes/tika-pipes-core/src/test/java/org/apache/tika/pipes/core/PipesClientTest.java
tika-pipes/tika-pipes-core/src/test/resources/test-documents/mock/timeout-10s.xml

TIKA-4497 -- allow per file timeouts in tika-pipes
