apache/tika

tika-core/src/main/java/org/apache/tika/sax/RichTextContentHandler.java, tika-core/src/test/java/org/apache/tika/sax/RichTextContentHandlerTest.java, tika-server/src/main/java/org/apache/tika/server/resource/TikaResource.java, tika-server/src/main/java/org/apache/tika/server/resource/UnpackerResource.java
…rver so users if needing it don't need to depend upon tika-server
=> Refector RichTextContentHandler for TIKA-1870 contributed by nhoj.patrick

tika-test-resources/pom.xml, tika-test-resources/src/test/resources/org/apache/tika/parser/ner/opennlp/ModelGetter.groovy
This PR brings proxy based downloading feature from 1.x branch to 2.x
Closes  TIKA-1816
=> TIKA1816 : NER model download via maven proxy ( from 1.x to 2.x)

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
Identified magic bytes based on FHT analysis on Polar-Data in class #CSCI599
=> updated mime magic for cab, quicktime, fits and netcdf 

tika-parsers/src/main/java/org/apache/tika/parser/journal/TEIParser.java
=> fix for TIKA-1926 contributed by hasanayesha

tika-parsers/src/main/java/org/apache/tika/parser/ner/nltk/NLTKNERecogniser.java
@chrismattmann please review the changes. thanks
=> Tika 1917 - Enable all entities received from NLTKRest Server

tika-parsers/src/main/java/org/apache/tika/parser/ner/grobid/GrobidNERecogniser.java
Grobid Quantities can also return information about the measurement type, one example could be : length. They are useful to analyse what type of measurements  exist
=> TIKA-1965 contributed by cmenekse

tika-core/src/main/java/org/apache/tika/sax/XHTMLContentHandler.java, tika-parsers/src/test/java/org/apache/tika/parser/html/HtmlParserTest.java, tika-parsers/src/test/resources/test-documents/head.html
While this fixes TIKA-1980, which is regression I caused in TIKA-1938, it might be good to have a second set of eyes make sure there isn't anything else I should test.
=> fix for TIKA-1980 contributed by naegelejd

tika-parsers/src/main/java/org/apache/tika/parser/ocr/TesseractOCRParser.java
Removed print statements for errors and made check for python static.
=> fix for TIKA-2031 contributed by Zarana-Parekh

tika-server/pom.xml
This PR addresses https://issues.apache.org/jira/browse/TIKA-2253
=> TIKA-2253 Obtain new Miredot license key and upgrade plugin version in tika-server

tika-parsers/src/main/java/org/apache/tika/parser/feed/FeedParser.java
Fixes https://issues.apache.org/jira/browse/TIKA-2269 + additional small improvement
=> Fix for Tika-2269

tika-core/src/main/java/org/apache/tika/language/LanguageIdentifier.java
=> Fix typo in Javadoc

tika-parsers/src/main/resources/org/apache/tika/parser/recognition/tf/InceptionVideoRestDockerfile
#install missing dependencies
#delete source files of OpenCV after building
=> TIKA-2322: update dockerfile

tika-parsers/src/main/java/org/apache/tika/parser/microsoft/xml/WordMLParser.java
You can simplify the initialization using a singleton set for SUPPORTED_TYPES
This change is untested.
=> SUPPORTED_TYPES is an immutable singleton set

tika-parsers/src/main/java/org/apache/tika/parser/ctakes/CTAKESUtils.java
https://issues.apache.org/jira/browse/TIKA-2332
=> TIKA-2332 Add SNOMED codes to server output

tika-server/Dockerfile, tika-server/pom.xml
Added local docker build based on dockerfile-maven-plugin as base to start publishing official builds.
=> TIKA-1518: Add local docker build based on dockerfile-maven-plugin

tika-core/src/main/java/org/apache/tika/mime/MimeTypesReader.java
This issue addresses https://issues.apache.org/jira/browse/TIKA-2639
=> TIKA-2639 Update freedesktop.org shared-mime-info-spec hyperlink in MimeTypesReader.java

tika-parent/pom.xml
=> Update to forbiddenapis v2.7

tika-parsers/src/main/java/org/apache/tika/parser/image/ImageMetadataExtractor.java
See https://issues.apache.org/jira/browse/TIKA-2954
=> Fix for TIKA-2954 contributed by chriszappia

CHANGES.txt, tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-parsers/src/main/java/org/apache/tika/parser/xliff/XLIFF12ContentHandler.java, tika-parsers/src/main/java/org/apache/tika/parser/xliff/XLIFF12Parser.java, tika-parsers/src/main/resources/META-INF/services/org.apache.tika.parser.Parser, tika-parsers/src/test/java/org/apache/tika/parser/xliff/XLIFF12ParserTest.java, tika-parsers/src/test/resources/test-documents/testXLIFF12.xlf
Adds a basic parser for XLIFF v1.2 files
=> TIKA-2975: Add parser for XLIFF v1.2 files

tika-parsers/src/main/java/org/apache/tika/parser/microsoft/onenote/JCID.java, tika-parsers/src/main/java/org/apache/tika/parser/microsoft/onenote/JCIDPropertySetTypeEnum.java, tika-parsers/src/main/java/org/apache/tika/parser/microsoft/onenote/OneNoteParser.java, tika-parsers/src/main/java/org/apache/tika/parser/microsoft/onenote/OneNotePtr.java, tika-parsers/src/main/java/org/apache/tika/parser/microsoft/onenote/OneNoteTreeWalker.java, tika-parsers/src/test/java/org/apache/tika/parser/microsoft/onenote/OneNoteParserTest.java
add author and timestamp support to tika 2224
=> add author support and last modified timestamp support

tika-parsers/src/main/java/org/apache/tika/parser/pdf/XFAExtractor.java, tika-parsers/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java
fix for https://issues.apache.org/jira/browse/TIKA-3138
=> fix for TIKA-3139 contributed by wiwi

tika-core/src/main/java/org/apache/tika/mime/MimeTypesReader.java
=> Fixing typo on SAX Parser exception

tika-app/src/test/java/org/apache/tika/cli/TikaCLITest.java
1.remove unnecessary import
2.reset outContent and errContent if they are not empty,prevent previous TikaCLI.main run output left.
3.add two test case
4.modify previous test case,use method getParamOutContent to run TikaCLI.main and get output string.
=> Modify TikaCLITest

tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java
1. fix parse arg "--client="
2. make the way of parse arg "--compare-file-magic" same as others
=> Modify some arg parse in TikaCLI

tika-parsers-advanced/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/sentiment/SentimentAnalysisParser.java, tika-parsers-advanced/tika-parser-nlp-module/src/test/resources/org/apache/tika/parser/sentiment/tika-config-sentiment-opennlp-cat.xml, tika-parsers-advanced/tika-parser-nlp-module/src/test/resources/org/apache/tika/parser/sentiment/tika-config-sentiment-opennlp.xml
Some bin files' url was updated.
=> Update urls of some bin files

tika-core/src/main/java/org/apache/tika/io/TemporaryResources.java
TestCase `org.apache.tika.image.HeifParserTest.testSimple` failed in windows because `TemporaryResources.close()` sometimes fail to delete tmp file.
We can make it `deleteOnExit` as it's only a temp file, as Windows will eventually delete them from time to time even through `deleteOnExit` failed.
=> Fix can't del tmp file in windows

tika-core/src/main/java/org/apache/tika/io/TikaInputStream.java
After we copy all data in `InputStream` to `file` and use new `InputStream` open from `file`, we should update `position` and `mark`
=> Modify TikaInputStream

tika-batch/src/test/java/org/apache/tika/batch/fs/FSBatchTestBase.java
1.modify method tearDown: If delete output directory root fail,try delete on exit.
2.simplify some code use collection.addAll
3.simplify some code use "for"
4.remove unnecessary import
=> Modify FSBatchTestBase

tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/detect/microsoft/ooxml/OPCPackageDetector.java
Use const which in class `PackageRelationshipTypes`.
Just like the `TODO` says.
=> Repalce const in OPCPackageDetector

tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java, tika-app/src/test/java/org/apache/tika/cli/TikaCLITest.java
For [TIKA-3044](https://issues.apache.org/jira/browse/TIKA-3044).
=> TIKA-3044 add -C/--content cli option using WriteOutContentHandler

tika-app/src/main/java/org/apache/tika/cli/BatchCommandLineBuilder.java, tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java, tika-batch/src/main/java/org/apache/tika/batch/BatchProcessDriverCLI.java, tika-batch/src/main/java/org/apache/tika/batch/fs/strawman/StrawManTikaAppDriver.java, tika-batch/src/test/java/org/apache/tika/batch/fs/FSBatchTestBase.java, tika-core/src/main/java/org/apache/tika/language/LanguageProfilerBuilder.java, tika-core/src/main/java/org/apache/tika/metadata/Metadata.java, tika-core/src/main/java/org/apache/tika/metadata/Property.java, tika-core/src/main/java/org/apache/tika/mime/MimeTypesFactory.java, tika-core/src/main/java/org/apache/tika/parser/external/ExternalParsersFactory.java, tika-core/src/test/java/org/apache/tika/MultiThreadedTikaTest.java, tika-core/src/test/java/org/apache/tika/sax/XHTMLContentHandlerTest.java, tika-eval/src/main/java/org/apache/tika/eval/TikaEvalCLI.java, tika-fuzzing/src/main/java/org/apache/tika/fuzzing/pdf/EvilCOSWriter.java, tika-langdetect/tika-langdetect-commons/src/test/java/org/apache/tika/langdetect/LanguageDetectorTest.java, tika-parser-modules/tika-parser-audiovideo-module/src/main/java/org/apache/tika/parser/mp3/Mp3Parser.java, tika-parser-modules/tika-parser-digest-commons/src/main/java/org/apache/tika/parser/digestutils/CommonsDigester.java, tika-parser-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/OutlookExtractor.java, tika-parser-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/dbf/DBFFileHeader.java, tika-parser-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/odf/OpenDocumentMetaParser.java, tika-parser-modules/tika-parser-text-module/src/main/java/org/apache/tika/parser/strings/StringsParser.java, tika-parser-modules/tika-parser-text-module/src/main/java/org/apache/tika/parser/txt/CharsetDetector.java, tika-server/src/main/java/org/apache/tika/server/TikaServerCli.java
Use method with empty array instead of pre size array.
Because it's more safe and faster.
See also this [blog](https://shipilev.net/blog/2016/arrays-wisdom-ancients/)
=> Modify some calls of method Collection.toArray

tika-core/src/test/java/org/apache/tika/fork/ForkParserTest.java, tika-eval/src/test/java/org/apache/tika/eval/ComparerBatchTest.java, tika-parser-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/epub/EpubParser.java, tika-parsers-extended/tika-parser-scientific-module/src/main/java/org/apache/tika/parser/netcdf/NetCDFParser.java
We can use try-with-resources to simplify the code.
=> Modify some code use try-with-resources

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
Added a namespace declaration because it may cause an error when processing XML because there is no namespace declaration.
=> fix for TIKA-3225 contributed by onozaty

tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-audiovideo-module/src/main/java/org/apache/tika/parser/mp4/MP4Parser.java
=> TIKA-3310 Check if MP4 file's compatible brands match any of the expected values

tika-server/tika-server-classic/src/main/java/org/apache/tika/server/classic/config/PDFServerConfig.java, tika-server/tika-server-classic/src/main/java/org/apache/tika/server/classic/config/TesseractServerConfig.java, tika-server/tika-server-classic/src/test/java/org/apache/tika/server/classic/TikaResourceTest.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/resource/TikaResource.java
TIKA-3320
Made TikaServer header names case insensitive
=> TIKA-3320 Added case-insensitivity to tika server ocr header names

tika-server/tika-server-classic/src/main/java/org/apache/tika/server/classic/config/PDFServerConfig.java, tika-server/tika-server-classic/src/main/java/org/apache/tika/server/classic/config/TesseractServerConfig.java, tika-server/tika-server-classic/src/test/java/org/apache/tika/server/classic/TikaResourceTest.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/ParseContextConfig.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/resource/TikaResource.java
Minor restructure and added missing javadoc on TikaServer.
No functional change.
Modified existing methods based on usage for clearer code.
=> Minor cleaning and added missing javadoc on TikaServer

tika-server/src/main/java/org/apache/tika/server/resource/TikaResource.java
Backporting main #415 
TIKA-3326
=> TIKA-3326 Branch 1x Backporting #415

.github/pull_request_template.md, .github/workflows/main-build.yml
This issue addresses https://issues.apache.org/jira/browse/TIKA-3311
=> [TIKA-3311] Add github workflows to Tika

tika-core/src/main/java/org/apache/tika/utils/AnnotationUtils.java
=> Fix up exception handling for invalid config

.asf.yaml
This issue addresses https://issues.apache.org/jira/browse/TIKA-3383
=> [TIKA-3383] Add .asf.yaml files to all Tika repositories

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/AbstractPDF2XHTML.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFParserConfig.java
=> TIKA-3361 Make ocrStrategy=Auto more intelligent

tika-server/README.md
=> TIKA-3497 bump versions in example commands for installing as a service.

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
This PR adds a new MIME type, as described in [TIKA-3559](https://issues.apache.org/jira/browse/TIKA-3559).
=> [TIKA-3559] Add MIME type for .webmanifest files

tika-parsers/pom.xml
=> TIKA-3601 - Update JSoup to fix CVE-2021-37714

tika-parent/pom.xml
=> log4j 2.16.0

README.md
This trivial issue addresses https://issues.apache.org/jira/browse/TIKA-3619
=> TIKA-3619 Augment README with build prerequisites

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/OOXMLExtractorFactory.java
=> [TIKA-3627] Fix OOXML parsing for multiple threads

tika-parent/pom.xml
This issue addresses https://issues.apache.org/jira/browse/TIKA-3635
=> TIKA-3635 Upgrade to rome 1.18.0

tika-translate/src/main/java/org/apache/tika/language/translate/impl/MarianTranslator.java, tika-translate/src/main/resources/META-INF/services/org.apache.tika.language.translate.Translator, tika-translate/src/main/resources/org/apache/tika/language/translate/impl/translator.marian.properties, tika-translate/src/test/java/org/apache/tika/language/translate/impl/MarianTranslatorTest.java
Implements a new MarianTranslator to provide support for Marian NMT, a popular machine translation engine framework,
=> TIKA-3636: Add MarianTranslator to tika-translate

tika-parent/pom.xml
=> [TIKA-3638] Upgraded log4j to 1.27.1

tika-app/pom.xml
The pull request for https://issues.apache.org/jira/browse/TIKA-3650
=> TIKA-3650 - Removal of duplicate javax/* classes from tika-app jar

.github/dependabot.yml
This PR addresses https://issues.apache.org/jira/browse/TIKA-3651
=> TIKA-3651 Activate Dependabot on Tika main branch

tika-translate/pom.xml, tika-translate/src/main/java/org/apache/tika/language/translate/impl/GoogleTranslator.java, tika-translate/src/main/java/org/apache/tika/language/translate/impl/JoshuaNetworkTranslator.java, tika-translate/src/main/java/org/apache/tika/language/translate/impl/Lingo24Translator.java, tika-translate/src/main/java/org/apache/tika/language/translate/impl/YandexTranslator.java
Usage of StringBuffer in one thread method was an overkill
=> TIKA-3649 fixes for static analysis report of module tika-translate

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-mail-module/src/test/java/org/apache/tika/parser/mail/RFC822ParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-mail-module/src/test/resources/test-documents/testRFC822-ARC
1024  is maybe a bit overkill for the X|DKIM|ARC headers lookahead ?
=> Fix email detection (TIKA-3687)

tika-parent/pom.xml
* https://issues.apache.org/jira/browse/TIKA-3749
* there should be no conflicts when merging the pull request branch into the *recent* `main` branch. If there are conflicts, please try to rebase the pull request branch on top of a freshly pulled `main` branch
* if you add new module that downstream users will depend upon add it to relevant group in `tika-bom/pom.xml`.
We will be able to faster integrate your pull request if these conditions are met. If you have any questions how to fix your problem or about using Tika in general, please sign up for the [Tika …
=> [TIKA-3749] upgrade maven-bundle-plugin

tika-pipes/tika-fetchers/tika-fetcher-http/pom.xml, tika-pipes/tika-fetchers/tika-fetcher-http/src/main/java/org/apache/tika/pipes/fetcher/http/HttpFetcher.java, tika-pipes/tika-fetchers/tika-fetcher-http/src/test/java/org/apache/tika/pipes/fetcher/http/HttpFetcherTest.java
=> [TIKA-3776] Fix HttpFetcher not honouring filename

tika-core/src/main/java/org/apache/tika/detect/TextStatistics.java
According to what characters are encoded in UTF8, we should count the number of bytes from 0xf8 to 0x100 instead of 0xf80 to 0x100 which is apparently a typo.
* commits are squashed into a single …
=> Fix a typo in Text Detector

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-cad-module/src/main/java/org/apache/tika/parser/dwg/DWGReadParser.java
Fixes for Parsing DWG files using DWG read Parser identified during testing
=> TIKA-3883 Fixes for Parsing DWG files using DWG read

tika-core/src/test/java/org/apache/tika/metadata/TestMetadata.java
=> [TIKA-3944] fix flaky test in tika-core

tika-parent/pom.xml, tika-parsers/tika-parsers-extended/tika-parser-scientific-module/pom.xml
=> TIKA-3967 bump geoapi

tika-core/src/main/java/org/apache/tika/metadata/PDF.java, tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDMetadataExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/xmpschemas/XMPSchemaIllustrator.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/resources/test-documents/testPDF_AdobeIllustrator.pdf
* the issue ID (`TIKA-2689`)
- and placed in front of your commit messages surrounded by square brackets (`[TIKA-2689] Issue or pull request title`) …
=> TIKA-2689 -- add detection for pdf-based illustrator files at parse time for PDFs

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/OOXMLExtractorFactory.java
=> TIKA-3990 -- close pkg for regular InputStreams

tika-integration-tests/tika-pipes-s3-integration-tests/src/test/resources/tika-config-s3-integration-test.xml, tika-pipes/tika-fetchers/tika-fetcher-s3/src/main/java/org/apache/tika/pipes/fetcher/s3/S3Fetcher.java
=> TIKA-3993 -- improve S3Fetcher backoff configurability

CHANGES.txt, tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/mime/TestMimeTypes.java
* the issue ID (`TIKA-3991`)
- and placed in front of your commit messages surrounded by square brackets (`[TIKA-3991] Issue or pull request title`) …
=> TIKA-3991 -- Add detection for canon raw: crw, cr2 and cr3

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
=> TIKA-3994 -- improve detection of audio/mpeg

tika-app/src/main/java/org/apache/tika/batch/DigestingAutoDetectParserFactory.java, tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java, tika-app/src/main/java/org/apache/tika/gui/TikaGUI.java, tika-core/src/main/java/org/apache/tika/parser/AutoDetectParser.java, tika-core/src/main/java/org/apache/tika/parser/DigestingParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-digest-commons/src/main/java/org/apache/tika/parser/digestutils/CommonsDigesterFactory.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/AutoDetectParserConfigTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/BouncyCastleDigestingParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/DigestingParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/RecursiveParserWrapperTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/resources/configs/tika-config-digests-skip-container.xml, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/resource/TikaResource.java
=> TIKA--4007 -- allow users to turn of digesting for the container document

CHANGES.txt, tika-core/src/main/java/org/apache/tika/metadata/PDF.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/AbstractPDF2XHTML.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java
* the issue ID (`TIKA-4012`)
- and placed in front of your commit messages surrounded by square brackets (`[TIKA-4012] Issue or pull request title`) …
=> TIKA-4012 -- improve extraction of embedded docs in PDFs by looking beyond names tree and annotations

CHANGES.txt, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-webarchive-module/src/main/java/org/apache/tika/parser/warc/WARCParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-webarchive-module/src/test/java/org/apache/tika/parser/warc/WARCParserTest.java
=> TIKA-4018 -- improve extraction of metadata from warc

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-core/src/test/resources/org/apache/tika/mime/test_subrip.srt, tika-core/src/test/resources/org/apache/tika/mime/test_ttml.ttml
Add pattern of detection and mimetypes for subtitles format including DVD-IFO, EBU-STL, SUBRIP and TTML
* Tika is …
=> [TIKA-4028] Provide mimetypes for subtitles format

tika-parent/pom.xml
=> bump-jackson-databind

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/mime/OneOffMimeTest.java
=> Add a bunch of mimes

tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/reports/Report.java, tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/reports/ResultsReporter.java, tika-eval/tika-eval-app/src/main/resources/comparison-reports.xml
=> TIKA-4100 -- fix apparent infinite loop in some tika-eval sql updates

tika-core/src/main/java/org/apache/tika/metadata/Office.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/detect/microsoft/POIFSContainerDetector.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/AbstractPOIFSExtractor.java
=> TIKA-4091 -- further refinements

tika-parent/pom.xml
=> TIKA-4129 -- upgrade dependencies that require java 11.

tika-parent/pom.xml, tika-parsers/tika-parsers-extended/tika-parser-scientific-module/pom.xml
@tballison one more step forward :)
apache.sis still have issues (please see correspondent mail thread)
While building with Java-17 in PATH got error in tests:
```
[INFO] Apache Tika Deep Learning (powered by DL4J) ........ FAILURE [  3.616 s]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.053 s <<< FAILURE! -- in org.apache.tika.dl.imagerec.DL4JVGG16NetTest
[ERROR] org.apache.tika.dl.imagerec.DL4JVGG16NetTest.recognise -- Time elapsed: 0.051 s <<< ERROR!
org.apache.tika.exception.TikaConfigException: Pretrained model file failed checksum. If this error persists, please open an issue at https://github.com/eclipse/deeplearning4j.
at org.apache.tika.dl.imagerec.DL4JVGG16Net.initialize(DL4JVGG16Net.java:123)
at …
```
=> [TIKA-3948] switching to the SNAPSHOT version of apache.sis

tika-core/src/main/java/org/apache/tika/metadata/filter/CaptureGroupMetadataFilter.java, tika-core/src/test/java/org/apache/tika/metadata/filter/TestMetadataFilter.java, tika-core/src/test/resources/org/apache/tika/config/TIKA-4133-capture-group-overwrite.xml, tika-core/src/test/resources/org/apache/tika/config/TIKA-4133-capture-group.xml
=> TIKA-4133 -- add a capture group metadatafilter

tika-core/src/main/java/org/apache/tika/pipes/PipesServer.java, tika-core/src/main/java/org/apache/tika/pipes/pipesiterator/PipesIterator.java, tika-core/src/main/java/org/apache/tika/sax/BasicContentHandlerFactory.java
=> TIKA-4149 -- PipesServer should include throwOnWriteLimitReached

CHANGES.txt, tika-app/pom.xml
=> TIKA-4150 -- shade commons-io in tika-app to avoid conflicts with Hadoop

CHANGES.txt, tika-app/pom.xml
=> TIKA-4150 - revert shading

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-core/src/test/java/org/apache/tika/mime/RFC822DetectionTest.java
=> TIKA-4153 -- tighten RFC822 detection

tika-parsers/tika-parsers-ml/tika-dl/src/test/java/org/apache/tika/dl/imagerec/DL4JInceptionV3NetTest.java, tika-parsers/tika-parsers-ml/tika-dl/src/test/java/org/apache/tika/dl/imagerec/DL4JVGG16NetTest.java
=> fix dl4j unit tests to handle 403 on model download

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
=> TIKA-4174 correct mime type for sip pcap

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/epub/EncryptionParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/epub/EpubParser.java
=> TIKA-4176 -- throw EncryptedDocumentException for DRM protected epubs

tika-parsers/tika-parsers-ml/tika-age-recogniser/pom.xml
=> TIKA-4179 -- downgrade zookeeper

tika-core/src/test/java/org/apache/tika/detect/MimeDetectionWithNNTest.java, tika-core/src/test/java/org/apache/tika/mime/MimeDetectionTest.java, tika-core/src/test/java/org/apache/tika/mime/ProbabilisticMimeDetectionTest.java
=> TIKA-4184 -- fix couple of broken assertNotNulls

CHANGES.txt, tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/java/org/apache/tika/parser/sqlite3/SQLite3DBParser.java, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/java/org/apache/tika/parser/sqlite3/SQLite3Parser.java, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/test/java/org/apache/tika/parser/sqlite3/SQLite3ParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-jdbc-commons/src/main/java/org/apache/tika/parser/jdbc/AbstractDBParser.java
=> TIKA-4187 -- improve detection of sqlite3 based file formats

tika-core/src/main/java/org/apache/tika/pipes/pipesiterator/CallablePipesIterator.java
=> TIKA-4189 -- small bug fix in CallablePipesIterator -- should pause when trying to add semaphore

tika-core/src/main/java/org/apache/tika/detect/AutoDetectReader.java, tika-core/src/main/java/org/apache/tika/detect/CompositeEncodingDetector.java, tika-core/src/main/java/org/apache/tika/metadata/TikaCoreProperties.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/test/java/org/apache/tika/parser/html/HtmlParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-text-module/src/test/java/org/apache/tika/parser/txt/TXTParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/RecursiveParserWrapperTest.java
=> TIKA-4195 -- jsoup parser shouldn't conceal backoff to default encoding

CHANGES.txt, tika-app/pom.xml, tika-batch/pom.xml, tika-eval/tika-eval-app/pom.xml, tika-eval/tika-eval-core/pom.xml, tika-fuzzing/pom.xml, tika-java7/pom.xml, tika-server/tika-server-core/pom.xml, tika-translate/pom.xml, tika-xmp/pom.xml
=> TIKA-4191 -- reduce tika-core's scope to "provided" where possible

tika-parent/pom.xml, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/java/org/apache/tika/parser/geopkg/GeoPkgDBParser.java, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/java/org/apache/tika/parser/geopkg/GeoPkgParser.java, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/java/org/apache/tika/parser/geopkg/GeoPkgTableReader.java, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/java/org/apache/tika/parser/sqlite3/SQLite3DBParser.java, tika-parsers/tika-parsers-extended/tika-parser-sqlite3-module/src/main/resources/META-INF/services/org.apache.tika.parser.Parser
=> TIKA-4198 -- create separate geopkg parser to skip some blob columns

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-apple-module/src/main/java/org/apache/tika/parser/iwork/IWorkPackageParser.java
=> TIKA-4201 -- add hard limit to inputstream#read in IWorkParser's detectType

tika-core/src/main/java/org/apache/tika/metadata/PDF.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/OCRPageCounter.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java
=> TIKA-4202 -- add ocr page count to metadata for PDFs

tika-eval/tika-eval-app/pom.xml, tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/AbstractProfiler.java, tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/ExtractProfiler.java, tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/db/Cols.java
=> TIKA-4205 -- improve Profile mode

tika-core/src/main/java/org/apache/tika/metadata/PDF.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/AbstractPDF2XHTML.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/OCRPageCounter.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/ocr/TesseractOCRParserTest.java
=> TIKA-4202 -- actually add counter for pages to be ocr'd in PDFs

tika-pipes/tika-pipes-reporters/tika-pipes-reporter-jdbc/src/main/java/org/apache/tika/pipes/reporters/jdbc/JDBCPipesReporter.java
=> TIKA-4213 -- improve jdbc pipes reporter

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/XSLFPowerPointExtractorDecorator.java
=> TIKA-4211 -- first attempt/shot in the dark

tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java, tika-core/src/main/java/org/apache/tika/Tika.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/TikaServerProcess.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/resource/TikaResource.java, tika-server/tika-server-core/src/test/java/org/apache/tika/server/core/TikaVersionTest.java, tika-server/tika-server-core/src/test/java/org/apache/tika/server/core/TikaWelcomeTest.java
=> TIKA-4215 -- avoid loading all of Tika() just to get the version in tika-server

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
=> TIKA-4217 -- require whitespace at end of magic for bitmap files

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/XFAExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java
=> TIKA-4171 -- fix regression when field value is missing in XFA

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pkg-module/src/main/java/org/apache/tika/parser/pkg/CompressorParser.java
=> TIKA-4221 -- temporary workaround

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pkg-module/src/main/java/org/apache/tika/parser/pkg/PackageParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-zip-commons/src/main/java/org/apache/tika/detect/zip/DefaultZipContainerDetector.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-zip-commons/src/main/java/org/apache/tika/detect/zip/TikaArchiveStreamFactory.java
=> TIKA-4220 -- temporary workaround for tar detection regression

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml
=> TIKA-4222 -- add glob based detection for openscad

tika-core/src/main/resources/org/apache/tika/mime/tika-mimetypes.xml, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/mime/TestMimeTypes.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/resources/test-documents/testICalendar_w_prodId.ics
=> TIKA-4244 -- improve ics detection

tika-core/src/main/java/org/apache/tika/pipes/PipesServer.java
* metadata was not getting sent to the fetch process
=> TIKA-4252: fix metadata issue

tika-core/src/main/java/org/apache/tika/extractor/ParentContentHandler.java, tika-core/src/main/java/org/apache/tika/parser/RecursiveParserWrapper.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-ocr-module/src/main/java/org/apache/tika/parser/ocr/TesseractOCRConfig.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-ocr-module/src/main/java/org/apache/tika/parser/ocr/TesseractOCRParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/ocr/TesseractOCRParserTest.java
=> TIKA-4256 -- allow inlining of ocr'd content in the RecursiveParserWrapper

tika-core/src/main/java/org/apache/tika/metadata/filter/ClearByAttachmentTypeMetadataFilter.java, tika-core/src/test/java/org/apache/tika/metadata/filter/TestMetadataFilter.java, tika-core/src/test/resources/org/apache/tika/config/TIKA-4261-clear-by-embedded-type.xml
=> TIKA-4261 -- add attachment type metadata filter

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pkg-module/src/main/java/org/apache/tika/parser/pkg/CompressorParser.java
=> TIKA-4221 -- revert workaround

tika-core/src/main/java/org/apache/tika/metadata/TikaCoreProperties.java, tika-core/src/main/java/org/apache/tika/parser/RecursiveParserWrapper.java, tika-core/src/main/java/org/apache/tika/sax/RecursiveParserWrapperHandler.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-mail-module/src/main/java/org/apache/tika/parser/mail/MailContentHandler.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-mail-module/src/test/java/org/apache/tika/parser/mail/RFC822ParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/AbstractPOIFSExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/OutlookExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/pst/OutlookPSTParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/pst/PSTMailItemParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/OutlookParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/pst/OutlookPSTParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-package/src/test/java/org/apache/tika/parser/microsoft/POIContainerExtractionTest.java
=> Tika-4268 -- improve embedded resource path naming, esp for msg and email-based formats

CHANGES.txt, tika-core/src/test/java/org/apache/tika/TikaIT.java, tika-parent/pom.xml
=> Prep for 3.0.0-BETA2 release

tika-pipes/tika-fetchers/tika-fetcher-microsoft-graph/src/main/java/org/apache/tika/pipes/fetchers/microsoftgraph/MicrosoftGraphFetcher.java, tika-pipes/tika-fetchers/tika-fetcher-microsoft-graph/src/main/java/org/apache/tika/pipes/fetchers/microsoftgraph/config/MicrosoftGraphFetcherConfig.java, tika-pipes/tika-fetchers/tika-fetcher-microsoft-graph/src/test/java/org/apache/tika/pipes/fetchers/microsoftgraph/MicrosoftGraphFetcherTest.java
wrong config class name
needs to be Fetcher-class-name + "Config"
=> fix wrongly named config class

tika-core/src/main/java/org/apache/tika/metadata/filter/CaptureGroupMetadataFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/ClearByAttachmentTypeMetadataFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/ClearByMimeMetadataFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/CompositeMetadataFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/DateNormalizingMetadataFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/ExcludeFieldMetadataFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/FieldNameMappingFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/GeoPointMetadataFilter.java, tika-core/src/main/java/org/apache/tika/metadata/filter/IncludeFieldMetadataFilter.java, tika-serialization/src/main/java/org/apache/tika/serialization/TikaJsonSerializer.java
=> TIKA-4289 -- improve serializability for the metadatafilters

tika-pipes/tika-pipes-iterators/tika-pipes-iterator-csv/src/main/java/org/apache/tika/pipes/pipesiterator/csv/CSVPipesIterator.java
TIKA-4290 Throw created TikaConfigException
=> TIKA-4290 Throw created TikaConfigException

tika-serialization/src/main/java/org/apache/tika/serialization/ParseContextDeserializer.java, tika-serialization/src/main/java/org/apache/tika/serialization/ParseContextSerializer.java, tika-serialization/src/main/java/org/apache/tika/serialization/TikaJsonDeserializer.java, tika-serialization/src/main/java/org/apache/tika/serialization/TikaJsonSerializer.java, tika-server/tika-server-standard/src/test/java/org/apache/tika/server/standard/TikaPipesTest.java
=> TIKA-4294 -- further simplifications

tika-parsers/tika-parsers-extended/tika-parser-scientific-module/src/main/java/org/apache/tika/parser/geoinfo/GeographicInformationParser.java, tika-parsers/tika-parsers-ml/tika-dl/src/main/java/org/apache/tika/dl/imagerec/DL4JInceptionV3Net.java, tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/ner/grobid/GrobidNERecogniser.java
TIKA-4290 Prevent resource leaks
=> TIKA-4290 Used try-with-resources for some Closeables. 

tika-core/src/main/java/org/apache/tika/config/Param.java, tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/reports/Report.java, tika-example/src/main/java/org/apache/tika/example/TextStatsFromTikaEval.java
TIKA-4290 Removed unused collections and a method call
=> TIKA-4290 Removed unused collections and a method call

tika-core/src/main/java/org/apache/tika/pipes/extractor/EmbeddedDocumentBytesConfig.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFParserConfig.java, tika-serialization/src/main/java/org/apache/tika/serialization/TikaJsonSerializer.java
=> small improvements to serialization

tika-core/src/main/java/org/apache/tika/metadata/Metadata.java, tika-core/src/main/java/org/apache/tika/parser/external/ExternalParsersConfigReader.java, tika-eval/tika-eval-core/src/main/java/org/apache/tika/eval/core/textstats/TextProfileSignature.java, tika-example/src/main/java/org/apache/tika/example/RecentFiles.java, tika-langdetect/tika-langdetect-tika/src/main/java/org/apache/tika/langdetect/tika/LanguageProfilerBuilder.java, tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/ner/grobid/GrobidNERecogniser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-apple-module/src/main/java/org/apache/tika/parser/iwork/AutoPageNumberUtils.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-audiovideo-module/src/main/java/org/apache/tika/parser/mp3/Mp3Parser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-cad-module/src/main/java/org/apache/tika/parser/dwg/DWGReadFormatRemover.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-image-module/src/main/java/org/apache/tika/parser/image/PSDParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-xmp-commons/src/main/java/org/apache/tika/parser/xmp/JempboxExtractor.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/TikaServerConfig.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/resource/TikaMimeTypes.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/resource/TikaWelcome.java
TIKA-4290 Changed StringBuffers to StringBuilders/StringJoiner. StringBuffer has an overhead for single thread env
=> TIKA-4290 Changed StringBuffers to StringBuilders/StringJoiner.

tika-core/src/main/java/org/apache/tika/pipes/PipesServer.java, tika-core/src/main/java/org/apache/tika/pipes/pipesiterator/fs/FileSystemPipesIterator.java, tika-fuzzing/src/main/java/org/apache/tika/fuzzing/cli/FuzzingCLI.java, tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/journal/TEIDOMParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/main/java/org/apache/tika/parser/html/JSoupParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/epub/EpubParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-miscoffice-module/src/main/java/org/apache/tika/parser/epub/OPFParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/renderer/pdf/pdfbox/NoTextPDFRenderer.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/renderer/pdf/pdfbox/TextOnlyPDFRenderer.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/renderer/pdf/pdfbox/VectorGraphicsOnlyPDFRenderer.java, tika-server/tika-server-client/src/main/java/org/apache/tika/server/client/TikaClientCLI.java
TIKA-4290 Added static keyword to inner classes
=> TIKA-4290 Added static keyword to inner classes

tika-langdetect/tika-langdetect-tika/src/main/java/org/apache/tika/langdetect/tika/LanguageIdentifier.java
TIKA-4290 Replaced string concatenation in loop - for every loop previously a StringBuilder was implicitly created. It's performance related
* commits are squashed into a single one (or few …
=> TIKA-4290 Replaced string concatenation in loop

tika-core/src/main/java/org/apache/tika/pipes/PipesServer.java, tika-fuzzing/src/main/java/org/apache/tika/fuzzing/cli/FuzzingCLI.java, tika-parsers/tika-parsers-ml/tika-dl/src/main/java/org/apache/tika/dl/imagerec/DL4JInceptionV3Net.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/PropertyValue.java, tika-pipes/tika-emitters/tika-emitter-opensearch/src/main/java/org/apache/tika/pipes/emitter/opensearch/OpenSearchClient.java, tika-pipes/tika-pipes-reporters/tika-pipes-reporter-jdbc/src/main/java/org/apache/tika/pipes/reporters/jdbc/JDBCPipesReporter.java, tika-pipes/tika-pipes-reporters/tika-pipes-reporter-opensearch/src/main/java/org/apache/tika/pipes/reporters/opensearch/OpenSearchClient.java, tika-server/tika-server-core/src/main/java/org/apache/tika/server/core/FetcherStreamFactory.java
TIKA-4290 fixed args in logging calls
=> TIKA-4290 fixed args in logging calls

tika-core/src/main/java/org/apache/tika/pipes/PipesConfigBase.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/streamobj/RevisionManifestDataElementData.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/streamobj/StorageManifestDataElementData.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/streamobj/basic/CellIDArray.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/streamobj/basic/ExGUIDArray.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/streamobj/space/ObjectSpaceObjectStreamOfContextIDs.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/streamobj/space/ObjectSpaceObjectStreamOfOIDs.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/onenote/fsshttpb/streamobj/space/ObjectSpaceObjectStreamOfOSIDs.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-text-module/src/main/java/org/apache/tika/parser/txt/Icu4jEncodingDetector.java
TIKA-4290 Replaced loop with parametrized constructor call
Performance related
=> TIKA-4290 Replaced loop with parametrized constructor call

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/AbstractPDF2XHTML.java
=> TIKA-4299 -- clean up pagination in AbstractPDF2XHTML.

tika-core/src/main/java/org/apache/tika/metadata/listfilter/MetadataListFilter.java, tika-core/src/test/java/org/apache/tika/metadata/listfilter/MetadataListFilterTest.java, tika-core/src/test/resources/org/apache/tika/metadata/listfilter/metadatalistfilter-config.xml
=> TIKA-4341 -- fix MetadataListFilter's deserialization

tika-parent/pom.xml
=> TIKA-4348 -- downgrade log4j2

tika-core/src/main/java/org/apache/tika/metadata/writefilter/StandardWriteFilter.java, tika-core/src/main/java/org/apache/tika/metadata/writefilter/StandardWriteFilterFactory.java, tika-core/src/test/java/org/apache/tika/metadata/writefilter/StandardWriteFilterTest.java, tika-core/src/test/resources/org/apache/tika/config/TIKA-3695-exclude.xml
=> TIKA-4352 -- add an exclusion list in the StandardWriteFilter

tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java, tika-app/src/test/java/org/apache/tika/cli/TikaCLITest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/main/java/org/apache/tika/parser/pdf/PDFParserConfig.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pdf-module/src/test/java/org/apache/tika/parser/pdf/PDFParserTest.java
=> TIKA-4358 -- turn on extraction of incremental update metadata as default

tika-core/src/main/java/org/apache/tika/metadata/MAPI.java, tika-core/src/main/java/org/apache/tika/metadata/Office.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/OutlookExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/pst/PSTMailItemParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/OutlookParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/libpst/TestLibPstParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/pst/OutlookPSTParserTest.java
=> TIKA-4360 -- improve extraction of mapi metadata

tika-core/src/main/java/org/apache/tika/io/FilenameUtils.java, tika-core/src/test/java/org/apache/tika/io/FilenameUtilsTest.java
=> TIKA-4387 -- FilenameUtils should require that file extensions be ascii alphanumerics only.

tika-core/src/main/java/org/apache/tika/metadata/MAPI.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/msg/ExtendedMetadataExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/msg/TikaNameIdChunks.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/OutlookParserTest.java
=> TIKA-4389 cleanups for TIKA-4381

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/xwpf/XWPFStylesShim.java
I was looking at some Tika code with the vague idea of copying some of the docx extractor code to Apache POI.
My IDE highlighted that these fields could be final.
=> [MINOR] mark some fields as final

tika-parsers/tika-parsers-ml/pom.xml
=> TIKA-4400 -- move some modules to the sandbox profile

tika-core/src/main/java/org/apache/tika/metadata/MAPI.java, tika-core/src/main/java/org/apache/tika/metadata/RTFMetadata.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/OutlookExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/rtf/TextExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/OutlookParserTest.java
=> TIKA-4391 -- identify "inline" images within .msg files.

tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/reports/Report.java
=> TIKA-4413 -- use Zip64Mode.AlwaysWithCompatibility

tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/AbstractProfiler.java, tika-eval/tika-eval-app/src/main/resources/comparison-reports.xml, tika-eval/tika-eval-app/src/main/resources/profile-reports.xml
=> TIKA-4374 -- embedded file path names

tika-eval/tika-eval-app/src/main/java/org/apache/tika/eval/app/reports/Report.java
=> improve handling of the data descriptor retry in the zip detector

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/OutlookExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/test/java/org/apache/tika/parser/microsoft/OutlookParserTest.java
=> TIKA-4418 -- actually include title in body when injecting select metadata into the body for msg files

tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/main/java/org/apache/tika/parser/html/JSoupParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/main/resources/org/apache/tika/parser/html/self-closeable-tags.txt
=> TIKA-4419 -- experiment with custom list of self-closeable-tags.txt

tika-parent/pom.xml, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/main/java/org/apache/tika/parser/html/JSoupParser.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/main/resources/org/apache/tika/parser/html/self-closeable-tags.txt, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-html-module/src/test/java/org/apache/tika/parser/html/HtmlParserTest.java
=> TIKA-4419 -- workaround for jsoup change in behavior

tika-grpc/pom.xml
=> Tika 4318 fix issue with javadoc

tika-core/src/main/java/org/apache/tika/metadata/Geographic.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-image-module/src/main/java/org/apache/tika/parser/image/ImageMetadataExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-image-module/src/test/java/org/apache/tika/parser/image/HeifParserTest.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-image-module/src/test/java/org/apache/tika/parser/image/JpegParserTest.java
=> TIKA-4425 - extract gps timestamp

tika-core/src/main/java/org/apache/tika/metadata/Office.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/OPCPackageWrapper.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/XSSFExcelExtractorDecorator.java
=> TIKA-4410 -- further additions

tika-core/src/main/java/org/apache/tika/config/TikaConfig.java, tika-core/src/main/java/org/apache/tika/utils/XMLReaderUtils.java, tika-core/src/test/java/org/apache/tika/config/TikaConfigTest.java, tika-core/src/test/java/org/apache/tika/utils/XMLReaderUtilsTest.java, tika-core/src/test/resources/org/apache/tika/config/TIKA-4427-max-num-reuses.xml, tika-core/src/test/resources/org/apache/tika/config/TIKA-4427-no-sax-pool.xml
=> TIKA-4427 -- allow pool size to be zero, and set a configurable max reuse value

tika-core/src/main/java/org/apache/tika/metadata/writefilter/StandardWriteFilter.java, tika-core/src/test/java/org/apache/tika/metadata/writefilter/StandardWriteFilterTest.java
=> TIKA-4433 -- improve handling of null values

tika-core/src/main/java/org/apache/tika/metadata/Office.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/HSLFExtractor.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/OOXMLWordAndPowerPointTextHandler.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/SXSLFPowerPointExtractorDecorator.java, tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-microsoft-module/src/main/java/org/apache/tika/parser/microsoft/ooxml/XSLFPowerPointExtractorDecorator.java
=> TIKA-4434 -- extract more info out of ppt/pptx

tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java, tika-fuzzing/src/main/java/org/apache/tika/fuzzing/pdf/EvilCOSWriter.java, tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/journal/JournalParser.java, tika-translate/src/main/java/org/apache/tika/language/translate/impl/MarianTranslator.java
https://issues.apache.org/jira/browse/TIKA-4436
I've found some unclosed resource that may leading resource leak, and I'm willing to fix it 
1、tika-app/src/main/java/org/apache/tika/cli/TikaCLI.java#compareFileMagic BufferedReader r
2、tika-fuzzing/src/main/java/org/apache/tika/fuzzing/pdf/EvilCOSWriter.java#doWriteSignature InputStream dataToSign
3、tika-parsers/tika-parsers-ml/tika-parser-nlp-module/src/main/java/org/apache/tika/parser/journal/JournalParser.java#parse InputStream pdfStream
4、tika-translate/src/main/java/org/apache/tika/language/translate/impl/MarianTranslator.java#translate  BufferedReader fileReader
5、tika-translate/src/main/java/org/apache/tika/language/translate/impl/MarianTranslator.java#processWithLocalMarian BufferedReader stdOutReader
=> TIKA-4436 Fix some potential resource leak

.asf.yaml
=> Auto-link commits to TIKA Jira issues

tika-core/src/test/java/org/apache/tika/utils/XMLReaderUtilsTest.java
=> TIKA-4471 -- add unit tests to confirm defense against xxe in sax, dom and stax.

tika-core/src/test/java/org/apache/tika/utils/XMLReaderUtilsTest.java, tika-parent/pom.xml
=> TIKA-4471 -- fix i18n for new unit tests

tika-core/src/main/java/org/apache/tika/utils/XMLReaderUtils.java, tika-integration-tests/pom.xml, tika-integration-tests/tika-woodstox-tests/pom.xml, tika-integration-tests/tika-woodstox-tests/src/test/java/org/apache/tika/woodstox/WoodstoxXMLReaderUtilsTest.java
=> TIKA-4482 -- don't fail if woodstox is on the classpath

.github/workflows/main-jdk25-build.yml
=> TIKA-4496 - bump workflow from jdk23 to jdk25

tika-parent/pom.xml
=> TIKA-4448 -- bump junit to 6.0.0
